// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildDiagnosticsReport() {
  return window['go']['main']['App']['BuildDiagnosticsReport']();
}

export function CheckInstalledState() {
  return window['go']['main']['App']['CheckInstalledState']();
}

export function CleanCursorData() {
  return window['go']['main']['App']['CleanCursorData']();
}

export function DetectBrowsers() {
  return window['go']['main']['App']['DetectBrowsers']();
}

export function EnrollDevice(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['EnrollDevice'](arg1, arg2, arg3, arg4, arg5);
}

export function ExportDiagnosticsBundle() {
  return window['go']['main']['App']['ExportDiagnosticsBundle']();
}

export function GetAdminPolicyGuide() {
  return window['go']['main']['App']['GetAdminPolicyGuide']();
}

export function GetAgentStatus() {
  return window['go']['main']['App']['GetAgentStatus']();
}

export function GetBrowserProtectionStatus() {
  return window['go']['main']['App']['GetBrowserProtectionStatus']();
}

export function GetClaudeCodeIntegrationOverview() {
  return window['go']['main']['App']['GetClaudeCodeIntegrationOverview']();
}

export function GetClaudeCodeIntegrationStatus() {
  return window['go']['main']['App']['GetClaudeCodeIntegrationStatus']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCursorCleanupPreview() {
  return window['go']['main']['App']['GetCursorCleanupPreview']();
}

export function GetCursorIntegrationStatus() {
  return window['go']['main']['App']['GetCursorIntegrationStatus']();
}

export function GetDiagnosticsSnapshot() {
  return window['go']['main']['App']['GetDiagnosticsSnapshot']();
}

export function GetEnrollmentDefaults() {
  return window['go']['main']['App']['GetEnrollmentDefaults']();
}

export function GetExtensionStatus() {
  return window['go']['main']['App']['GetExtensionStatus']();
}

export function GetGitHubCopilotIntegrationStatus() {
  return window['go']['main']['App']['GetGitHubCopilotIntegrationStatus']();
}

export function GetLaunchOnLogin() {
  return window['go']['main']['App']['GetLaunchOnLogin']();
}

export function GetProxyRecoveryStatus() {
  return window['go']['main']['App']['GetProxyRecoveryStatus']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetWindsurfIntegrationStatus() {
  return window['go']['main']['App']['GetWindsurfIntegrationStatus']();
}

export function ImportEnrollmentConfigFile() {
  return window['go']['main']['App']['ImportEnrollmentConfigFile']();
}

export function InstallClaudeCodeHook() {
  return window['go']['main']['App']['InstallClaudeCodeHook']();
}

export function InstallClaudeCodeHookForTarget(arg1) {
  return window['go']['main']['App']['InstallClaudeCodeHookForTarget'](arg1);
}

export function InstallCursorHook() {
  return window['go']['main']['App']['InstallCursorHook']();
}

export function InstallExtension(arg1, arg2) {
  return window['go']['main']['App']['InstallExtension'](arg1, arg2);
}

export function InstallGitHubCopilotHook() {
  return window['go']['main']['App']['InstallGitHubCopilotHook']();
}

export function InstallWindsurfHook() {
  return window['go']['main']['App']['InstallWindsurfHook']();
}

export function IsEnrolled() {
  return window['go']['main']['App']['IsEnrolled']();
}

export function RemoveClaudeCodeHook() {
  return window['go']['main']['App']['RemoveClaudeCodeHook']();
}

export function RemoveClaudeCodeHookForTarget(arg1) {
  return window['go']['main']['App']['RemoveClaudeCodeHookForTarget'](arg1);
}

export function RemoveCursorHook() {
  return window['go']['main']['App']['RemoveCursorHook']();
}

export function RemoveGitHubCopilotHook() {
  return window['go']['main']['App']['RemoveGitHubCopilotHook']();
}

export function RemoveWindsurfHook() {
  return window['go']['main']['App']['RemoveWindsurfHook']();
}

export function RepairAgentService(arg1) {
  return window['go']['main']['App']['RepairAgentService'](arg1);
}

export function RepairClaudeCodeHook() {
  return window['go']['main']['App']['RepairClaudeCodeHook']();
}

export function RepairClaudeCodeHookForTarget(arg1) {
  return window['go']['main']['App']['RepairClaudeCodeHookForTarget'](arg1);
}

export function RepairCursorHook() {
  return window['go']['main']['App']['RepairCursorHook']();
}

export function RepairGitHubCopilotHook() {
  return window['go']['main']['App']['RepairGitHubCopilotHook']();
}

export function RepairWindsurfHook() {
  return window['go']['main']['App']['RepairWindsurfHook']();
}

export function ResetSystemProxy() {
  return window['go']['main']['App']['ResetSystemProxy']();
}

export function RestartAgent(arg1) {
  return window['go']['main']['App']['RestartAgent'](arg1);
}

export function ScanCursorData() {
  return window['go']['main']['App']['ScanCursorData']();
}

export function SetLaunchOnLogin(arg1, arg2) {
  return window['go']['main']['App']['SetLaunchOnLogin'](arg1, arg2);
}

export function StartService(arg1) {
  return window['go']['main']['App']['StartService'](arg1);
}

export function StopService(arg1) {
  return window['go']['main']['App']['StopService'](arg1);
}

export function UninstallExtension(arg1, arg2) {
  return window['go']['main']['App']['UninstallExtension'](arg1, arg2);
}

export function UpdateSetting(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateSetting'](arg1, arg2, arg3);
}

export function UseEnrollmentLink(arg1) {
  return window['go']['main']['App']['UseEnrollmentLink'](arg1);
}

export function ValidateAdmin(arg1, arg2) {
  return window['go']['main']['App']['ValidateAdmin'](arg1, arg2);
}
