// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {cursorcleanup} from '../models';

export function BuildDiagnosticsReport():Promise<string>;

export function CheckInstalledState():Promise<main.InstalledState>;

export function CleanCursorData():Promise<cursorcleanup.Result>;

export function DetectBrowsers():Promise<Array<main.BrowserInfo>>;

export function EnrollDevice(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<main.EnrollResult>;

export function ExportDiagnosticsBundle():Promise<main.ExportResult>;

export function GetAdminPolicyGuide():Promise<main.AdminPolicyGuide>;

export function GetAgentStatus():Promise<main.AgentStatus>;

export function GetBrowserProtectionStatus():Promise<Array<main.BrowserProtectionStatus>>;

export function GetClaudeCodeIntegrationOverview():Promise<main.ClaudeCodeIntegrationOverview>;

export function GetClaudeCodeIntegrationStatus():Promise<main.ClaudeCodeIntegrationStatus>;

export function GetConfig():Promise<main.AgentConfig>;

export function GetCursorCleanupPreview():Promise<cursorcleanup.Preview>;

export function GetCursorIntegrationStatus():Promise<main.CursorIntegrationStatus>;

export function GetDiagnosticsSnapshot():Promise<main.DiagnosticsSnapshot>;

export function GetEnrollmentDefaults():Promise<main.EnrollmentDefaults>;

export function GetExtensionStatus():Promise<Array<main.BrowserInfo>>;

export function GetGitHubCopilotIntegrationStatus():Promise<main.GitHubCopilotIntegrationStatus>;

export function GetLaunchOnLogin():Promise<boolean>;

export function GetProxyRecoveryStatus():Promise<main.ProxyRecoveryStatus>;

export function GetSystemInfo():Promise<main.SystemInfo>;

export function GetWindsurfIntegrationStatus():Promise<main.WindsurfIntegrationStatus>;

export function ImportEnrollmentConfigFile():Promise<main.EnrollmentImportResult>;

export function InstallClaudeCodeHook():Promise<main.ActionResult>;

export function InstallClaudeCodeHookForTarget(arg1:string):Promise<main.ActionResult>;

export function InstallCursorHook():Promise<main.ActionResult>;

export function InstallExtension(arg1:string,arg2:string):Promise<void>;

export function InstallGitHubCopilotHook():Promise<main.ActionResult>;

export function InstallWindsurfHook():Promise<main.ActionResult>;

export function IsEnrolled():Promise<boolean>;

export function RemoveClaudeCodeHook():Promise<main.ActionResult>;

export function RemoveClaudeCodeHookForTarget(arg1:string):Promise<main.ActionResult>;

export function RemoveCursorHook():Promise<main.ActionResult>;

export function RemoveGitHubCopilotHook():Promise<main.ActionResult>;

export function RemoveWindsurfHook():Promise<main.ActionResult>;

export function RepairAgentService(arg1:string):Promise<void>;

export function RepairClaudeCodeHook():Promise<main.ActionResult>;

export function RepairClaudeCodeHookForTarget(arg1:string):Promise<main.ActionResult>;

export function RepairCursorHook():Promise<main.ActionResult>;

export function RepairGitHubCopilotHook():Promise<main.ActionResult>;

export function RepairWindsurfHook():Promise<main.ActionResult>;

export function ResetSystemProxy():Promise<main.ResetProxyResult>;

export function RestartAgent(arg1:string):Promise<void>;

export function ScanCursorData():Promise<cursorcleanup.Result>;

export function SetLaunchOnLogin(arg1:boolean,arg2:string):Promise<void>;

export function StartService(arg1:string):Promise<void>;

export function StopService(arg1:string):Promise<void>;

export function UninstallExtension(arg1:string,arg2:string):Promise<void>;

export function UpdateSetting(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UseEnrollmentLink(arg1:string):Promise<main.EnrollmentImportResult>;

export function ValidateAdmin(arg1:string,arg2:string):Promise<string>;
